// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_fSh1KtiPjzSvp7FGPdpuH2YyuWM15Os',
    appId: '1:996266014886:web:1c7dbc17a029fca4b5dc67',
    messagingSenderId: '996266014886',
    projectId: 'truck-link-project',
    authDomain: 'truck-link-project.firebaseapp.com',
    storageBucket: 'truck-link-project.firebasestorage.app',
    measurementId: 'G-C17L7QZB76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD93boSs7yp1OeisG3hh1_A21qfIZVqCO4',
    appId: '1:996266014886:android:b464882a37c8e30cb5dc67',
    messagingSenderId: '996266014886',
    projectId: 'truck-link-project',
    storageBucket: 'truck-link-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTexJLAcNsGpNb5EfG-pkoMDY44x-4Vwk',
    appId: '1:996266014886:ios:b645d0e2db8f66c1b5dc67',
    messagingSenderId: '996266014886',
    projectId: 'truck-link-project',
    storageBucket: 'truck-link-project.firebasestorage.app',
    iosBundleId: 'com.example.trucklink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTexJLAcNsGpNb5EfG-pkoMDY44x-4Vwk',
    appId: '1:996266014886:ios:b645d0e2db8f66c1b5dc67',
    messagingSenderId: '996266014886',
    projectId: 'truck-link-project',
    storageBucket: 'truck-link-project.firebasestorage.app',
    iosBundleId: 'com.example.trucklink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_fSh1KtiPjzSvp7FGPdpuH2YyuWM15Os',
    appId: '1:996266014886:web:0d8c0ad2c157ff8fb5dc67',
    messagingSenderId: '996266014886',
    projectId: 'truck-link-project',
    authDomain: 'truck-link-project.firebaseapp.com',
    storageBucket: 'truck-link-project.firebasestorage.app',
    measurementId: 'G-M4HQ1LR89S',
  );
}
